### ISSUE TITLE
配置导入成功却无法使用

### ISSUE THREAD

**Issue by Roiyaru** [zzzgydi/clash-verge#16]
2022-03-09 09:25:58 - [clash]: panic: The specified module could not be found.
2022-03-09 09:25:58 - [clash]: 
2022-03-09 09:25:58 - [clash]: goroutine 1 [running]:
2022-03-09 09:25:58 - [clash]: golang.org/x/sys/windows.(*LazyProc).mustFind(...)
2022-03-09 09:25:58 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:325
2022-03-09 09:25:58 - [clash]: golang.org/x/sys/windows.(*LazyProc).Addr(...)
2022-03-09 09:25:58 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:333
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener/device/wintun.CreateAdapter({0xb42737, 0x5}, {0xb42737, 0x5}, 0x126dfec0)
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/device/wintun/wintun_windows.go:69 +0x1f5
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUNWithRequestedGUID({0xb42737, 0x5}, 0x126dfec0, 0x2328)
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:104 +0x49
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUN({0xb42737, 0x5}, 0x2328)
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:96 +0x126
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener/tun.New(0x12433080, 0x124330c0, 0x12433780, {0x126f0860, 0x2, 0x2})
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/tun/adapter.go:287 +0xd8
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun.func2()
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:256 +0x31f
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun(0x12433080, 0x124330c0, {0x1, {{{0x0, 0xffffc6120001}, 0x12404100}, 0x10}, {0x126dfd00, 0x6}, 0x1, ...})
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:264 +0x542
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/hub/executor.updateTun(0x124336c0)
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:138 +0x102
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/hub/executor.ApplyConfig(0x124336c0, 0x1)
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:80 +0x130
2022-03-09 09:25:58 - [clash]: github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x0})
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/hub/hub.go:48 +0x17c
2022-03-09 09:25:58 - [clash]: main.main()
2022-03-09 09:25:58 - [clash]: 	github.com/Dreamacro/clash/main.go:99 +0x89d
2022-03-09 09:26:00 - profile enhanced status ok

以上是log，看起来是缺了文件。

**Comment by zzzgydi** [comment]
你这个是开启了tun模式吧，需要在`~/.config/clash-verge`下面放一个`wintun.dll`；

https://github.com/Dreamacro/clash/wiki/premium-core-features#windows

**Comment by Roiyaru** [comment]
> 你这个是开启了tun模式吧，需要在 `~/.config/clash-verge`下面放一个 `wintun.dll`；
> 
> [https://github.com/Dreamacro/clash/wiki/premium-core-features#windows ](https://github.com/Dreamacro/clash/wiki/premium-core-features#windows)

嗯，我开了tun。加了ddl后还是空白。
log如下：

2022-03-09 10:32:15 - [clash]: panic: %1 is not a valid Win32 application.
2022-03-09 10:32:15 - [clash]: 
2022-03-09 10:32:15 - [clash]: goroutine 1 [running]:
2022-03-09 10:32:15 - [clash]: golang.org/x/sys/windows.(*LazyProc).mustFind(...)
2022-03-09 10:32:15 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:325
2022-03-09 10:32:15 - [clash]: golang.org/x/sys/windows.(*LazyProc).Addr(...)
2022-03-09 10:32:15 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:333
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener/device/wintun.CreateAdapter({0xfc2737, 0x5}, {0xfc2737, 0x5}, 0x1272de70)
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/device/wintun/wintun_windows.go:69 +0x1f5
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUNWithRequestedGUID({0xfc2737, 0x5}, 0x1272de70, 0x2328)
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:104 +0x49
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUN({0xfc2737, 0x5}, 0x2328)
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:96 +0x126
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener/tun.New(0x12574f00, 0x12574f40, 0x12575600, {0x1273e840, 0x2, 0x2})
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/tun/adapter.go:287 +0xd8
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun.func2()
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:256 +0x31f
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun(0x12574f00, 0x12574f40, {0x1, {{{0x0, 0xffffc6120001}, 0x125160e0}, 0x10}, {0x1272dcb0, 0x6}, 0x1, ...})
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:264 +0x542
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/hub/executor.updateTun(0x12575540)
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:138 +0x102
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/hub/executor.ApplyConfig(0x12575540, 0x1)
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:80 +0x130
2022-03-09 10:32:15 - [clash]: github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x0})
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/hub/hub.go:48 +0x17c
2022-03-09 10:32:15 - [clash]: main.main()
2022-03-09 10:32:15 - [clash]: 	github.com/Dreamacro/clash/main.go:99 +0x89d
2022-03-09 10:32:17 - profile enhanced status ok
2022-03-09 10:32:20 - profile enhanced status ok
2022-03-09 10:32:29 - profile enhanced status ok
2022-03-09 10:32:29 - profile enhanced status ok
2022-03-09 10:32:32 - profile enhanced status ok
2022-03-09 10:32:36 - profile enhanced status ok
2022-03-09 10:32:37 - profile enhanced status ok

**Comment by Roiyaru** [comment]
> 

选择的配置文件在CFW/CFA/Clash.Mini中均正常使用

**Comment by zzzgydi** [comment]
当前对tun模式的支持还非常粗糙，看log感觉clash好像还是没找到dll，重启软件试试呢，如果还不行的话，暂时只能关掉tun了

**Comment by Roiyaru** [comment]
> 当前对tun模式的支持还非常粗糙，看log感觉clash好像还是没找到dll，重启软件试试呢，如果还不行的话，暂时只能关掉tun了

tun已经关掉，还是无法使用，软件显示空白。配置文件已上传
[r6Af5W45BNfs.yaml.txt](https://github.com/zzzgydi/clash-verge/files/8211370/r6Af5W45BNfs.yaml.txt)

**Comment by zzzgydi** [comment]
查到了，external-controller字段写成了`:9090`，少了ip。下个版本兼容一下这种写法，目前版本的话，就把这个字段改成`127.0.0.1:9090`吧

**Comment by Roiyaru** [comment]
> 
加了，还是读不到东西，Proximity、Connections和Logs选项卡是空白的。
小新Pro16，Win11_beta22000.527

**Comment by zzzgydi** [comment]
加了之后有没有重启软件，或者log是怎样的，有没有正常启动clash

**Comment by Roiyaru** [comment]
> 加了之后有没有重启软件，或者log是怎样的，有没有正常启动clash

重启后还是空白，Clash core那里看不到内核信息
log如下：

2022-03-09 12:42:04 - [clash]: panic: %1 is not a valid Win32 application.
2022-03-09 12:42:04 - [clash]: 
2022-03-09 12:42:04 - [clash]: goroutine 1 [running]:
2022-03-09 12:42:04 - [clash]: golang.org/x/sys/windows.(*LazyProc).mustFind(...)
2022-03-09 12:42:04 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:325
2022-03-09 12:42:04 - [clash]: golang.org/x/sys/windows.(*LazyProc).Addr(...)
2022-03-09 12:42:04 - [clash]: 	golang.org/x/sys@v0.0.0-20220114195835-da31bd327af9/windows/dll_windows.go:333
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener/device/wintun.CreateAdapter({0x932737, 0x5}, {0x932737, 0x5}, 0x1275feb0)
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/device/wintun/wintun_windows.go:69 +0x1f5
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUNWithRequestedGUID({0x932737, 0x5}, 0x1275feb0, 0x2328)
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:104 +0x49
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener/device.CreateTUN({0x932737, 0x5}, 0x2328)
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/device/tun_windows.go:96 +0x126
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener/tun.New(0x12432fc0, 0x12433000, 0x124336c0, {0x1276e870, 0x2, 0x2})
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/tun/adapter.go:287 +0xd8
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun.func2()
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:256 +0x31f
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/listener.ReCreateTun(0x12432fc0, 0x12433000, {0x1, {{{0x0, 0xffffc6120001}, 0x12404100}, 0x10}, {0x1275fcf0, 0x6}, 0x1, ...})
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/listener/listener.go:264 +0x542
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/hub/executor.updateTun(0x12433600)
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:138 +0x102
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/hub/executor.ApplyConfig(0x12433600, 0x1)
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/hub/executor/executor.go:80 +0x130
2022-03-09 12:42:04 - [clash]: github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x0})
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/hub/hub.go:48 +0x17c
2022-03-09 12:42:04 - [clash]: main.main()
2022-03-09 12:42:04 - [clash]: 	github.com/Dreamacro/clash/main.go:99 +0x89d
2022-03-09 12:42:06 - profile enhanced status ok

**Comment by zzzgydi** [comment]
知识盲点了。可能是程序处理生成的配置文件有问题；

debug方式，用默认的配置启动程序，即先不用自己的订阅配置，可以新建一个local类型空的profile，选择这个，然后看看是不是还是同样的问题。

**Comment by Roiyaru** [comment]
> 知识盲点了。可能是程序处理生成的配置文件有问题；
> 
> debug方式，用默认的配置启动程序，即先不用自己的订阅配置，可以新建一个local类型空的profile，选择这个，然后看看是不是还是同样的问题。

完全移除后新建本地配置切换到Proxies选项卡直接卡死。
log如下：
2022-03-09 18:11:45 - [clash]: time="2022-03-09T18:11:44+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
2022-03-09 18:11:45 - [clash]: time="2022-03-09T18:11:44+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
2022-03-09 18:11:46 - profile enhanced status ok
2022-03-09 18:12:50 - profile enhanced status ok
![屏幕截图 2022-03-09 181627](https://user-images.githubusercontent.com/36790001/157421673-cfef2373-5a8d-4a30-b7c8-d6c804dad5ae.png)

**Comment by zzzgydi** [comment]
emmm，这是Web页面有异常没捕获。这个是0.0.21的吗，如果不是的话，可以升一下看看。如果是的话，只能说删掉`~/.config/clash-verge`这个目录了，然后再打开程序看看是不是一切正常。。然后再加链接

**Comment by Roiyaru** [comment]
> emmm，这是Web页面有异常没捕获。这个是0.0.21的吗，如果不是的话，可以升一下看看。如果是的话，只能说删掉`~/.config/clash-verge`这个目录了，然后再打开程序看看是不是一切正常。。然后再加链接

现在正常了，我导入了没有转换规则的原始配置已经可以在系统代理模式下使用了。不过tun依旧用不了，配置文件中网飞与迪士尼+的规则没有生效，油管规则正常。

原始配置与log已上传，转换规则后不能用的配置在中午测试反馈时也上传了。

期待下一个版本

[2022-03-09-191156.log](https://github.com/zzzgydi/clash-verge/files/8214211/2022-03-09-191156.log)
[rI5p00flp8o5.yaml.txt](https://github.com/zzzgydi/clash-verge/files/8214212/rI5p00flp8o5.yaml.txt)

**Comment by zzzgydi** [comment]
终于可以了，感动啊。

tun模式的话，要装wintun.dll，而且还要管理员权限执行这个程序才行，巴拉巴拉一大堆的还没空去研究。

**Comment by Roiyaru** [comment]
> 

应该是配置文件里面有些规则软件读不出来导致的问题，可能开发者您需要一位非常熟悉clash内核朋友来协助开发。

**Comment by zzzgydi** [comment]
规则里确实有几个我没用过的字段，可能这会导致一些问题，profile和rule-provider。在这里慢慢等大佬来指导了。

**Comment by Roiyaru** [comment]
> 退出程序后，恢复原来的系统代理，也就是流量不走clash了，这是feature诶

这是clashmini代理异常抓到的log，被占用，我也不懂了。

2022-03-09T21:31:59+08:00 [ EROR ] Start Mixed(http+socks) server error: listen tcp :7891: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by zzzgydi** [comment]
那意思是clash-verge的gui进程关了，但是clash进程还活着且占着端口，是这样吗。。。你可以看看任务管理器，看看还有没有clash进程。

**Comment by Roiyaru** [comment]
> 那意思是clash-verge的gui进程关了，但是clash进程还活着且占着端口，是这样吗。。。你可以看看任务管理器，看看还有没有clash进程。

是有进程在占端口，我已经关了。我用几天看看会不会复现，会复现我想办法抓到log再来反馈。

**Comment by Roiyaru** [comment]
> 规则里确实有几个我没用过的字段，可能这会导致一些问题，profile和rule-provider。在这里慢慢等大佬来指导了。

0.0.22版本可以使用配置文件里的所有规则了。在系统代理模式下分流正常，只有UWP应用还是无连接；可能是由于UWP本身运行在沙盒中,默认情况下是不能直接访问localhost，这个应该是要另外适配。log已上传

新版本还有一个小bug，看不到配置的流量信息，两个配置都是用同一个订阅转换来转换。如图
[2022-03-10-093811.log](https://github.com/zzzgydi/clash-verge/files/8219641/2022-03-10-093811.log)
![屏幕截图 2022-03-10 094626](https://user-images.githubusercontent.com/36790001/157573253-a5431d21-2046-4954-80e7-b31cf7ceb91a.png)

**Comment by zzzgydi** [comment]
新版对`external-controller`作了处理，支持`:9090`的写法，还不能支持`9090`（偷个懒，虽然我也不知道clash支不支持仅端口）。Proxies 页面异常未处理的情况还不能复现，我用了rule-provider字段也没啥异常，如果后续还出现Proxies异常的话，可以留意留意，感谢。

另外我发现，tun模式有dll还不能用的原因可能是架构不一致，你之前可能用的`amd64`的，但是windows里的0.0.21版本之前的版本都是用的x86架构的clash，所以可能是这个原因。

现在，Windows版本的clash都改成使用amd64的了，现在还不知道会不会有什么坑。

**Comment by ileeoyo** [comment]
@zzzgydi 我也是一样的问题，不显示core版本号，log，proxy都是空。解决方法：先新建一个空白的local配置文件，选择该配置生效重启。然后正常添加远程配置文件就可以了。这应该算是bug

**Comment by Roiyaru** [comment]
> 新版对`external-controller`作了处理，支持`:9090`的写法，还不能支持`9090`（偷个懒，虽然我也不知道clash支不支持仅端口）。Proxies 页面异常未处理的情况还不能复现，我用了rule-provider字段也没啥异常，如果后续还出现Proxies异常的话，可以留意留意，感谢。
> 
> 另外我发现，tun模式有dll还不能用的原因可能是架构不一致，你之前可能用的`amd64`的，但是windows里的0.0.21版本之前的版本都是用的x86架构的clash，所以可能是这个原因。
> 
> 现在，Windows版本的clash都改成使用amd64的了，现在还不知道会不会有什么坑。

手动加了amd64的dll后管理员模式运行可以用tun了，tun模式下uwp也可以被代理而系统代理模式不行。下版本开始应该可以内置dll了。还有现在的延迟和速度比不上CFW和Mini，就感觉到很慢。
[Uploading 2022-03-10-104917.log…]()

**Comment by zzzgydi** [comment]
@ileeoyo 你这个问题，应该是上面提到的配置里有开启tun模式，但是缺少wintun.dll的问题。

**Comment by zzzgydi** [comment]
@Roiyaru uwp的问题，我看在cfw里也提到，它内置了一个程序用来处理这个问题的。然后慢的话，这个应该不会吧，如果大家都是用的同一个clash内核的话。除非还有别的黑魔法黑科技啥的，看看有没有大佬提供一下学习资料再研究了。目前先解决能用的问题，其次是好用，最好再解决性能问题。

**Comment by ileeoyo** [comment]
> @ileeoyo 你这个问题，应该是上面提到的配置里有开启tun模式，但是缺少wintun.dll的问题。

@zzzgydi 这个wintun.ddl我是有的，在~/.config/clash-verge目录。目前我tun模式有点问题。 #19 
@Roiyaru 你用tun模式有遇到我这个问题吗

**Comment by zzzgydi** [comment]
另外，突然意识到对远程配置的处理，在0.0.21和0.0.22都存在一定的bug。

bug原因，增强配置模式让用户提供的配置越过了程序的控制（尽管不开启也会存在这个问题），部分配置字段导致程序界面异常，目前已知远程配置里的tun字段大概率会导致异常。（如果还有字段导致了异常，可以issue补充）

这个增强模式在这些字段上的处理逻辑是当作feature来设计，只不过写成了bug。后面会修复成，没有任何增强模式的profile都不执行对应的逻辑即可。

目前版本想要修复这个问题的话，可以采用自定义脚本处理。new一个profile，选择script类型。脚本编辑如下：

```javascript
function main(params) {
    delete params["tun"];
    return params;
}
```

**Comment by ileeoyo** [comment]
> 知远程配置里的tun

这是导致 #19 的原因吗？客户端tun配置和配置文件的tun字段会有不一样的地方，可能不是用户预期结果。可以已为tun功能做一个3选一开关，分别为：“关”，“覆盖配置文件“，”default（使用配置文件的的tun配置）“。选择”覆盖配置文件时“，需要在客户端界面提供一个手动填写tun配置的入口。

**Comment by Roiyaru** [comment]
> > @ileeoyo 你这个问题，应该是上面提到的配置里有开启tun模式，但是缺少wintun.dll的问题。
> 
> @zzzgydi 这个wintun.ddl我是有的，在~/.config/clash-verge目录。目前我tun模式有点问题。 #19 @Roiyaru 你用tun模式有遇到我这个问题吗

我的tun模式现在正常，配置文件里的规则也可以用

**Comment by zzzgydi** [comment]
@ileeoyo 这个可以提个feature issue，也可以征集一下意见和建议，后面再仔细琢磨琢磨怎么设计好一点。

**Comment by ileeoyo** [comment]
> > > @ileeoyo 你这个问题，应该是上面提到的配置里有开启tun模式，但是缺少wintun.dll的问题。
> > 
> > 
> > @zzzgydi 这个wintun.ddl我是有的，在~/.config/clash-verge目录。目前我tun模式有点问题。 #19 @Roiyaru 你用tun模式有遇到我这个问题吗
> 
> 我的tun模式现在正常，配置文件里的规则也可以用

@Roiyaru 你的域名规则能正常命中吗？我的全都解析成IP，然后IP规则命中了
