### ISSUE TITLE
错误error: failed to run custom build command for `rquickjs-sys v0.1.7`

### ISSUE THREAD

**Issue by thestmitsuki** [zzzgydi/clash-verge#649]
在执行
'''yarn dev'''
时出现了报错
我已下载vs并勾选使用C++的桌面开发和下载clang，确保环境变量已添加，但是出现了
’‘’error: failed to run custom build command for `rquickjs-sys v0.1.7`‘’‘error: failed to run custom build command for `rquickjs-sys v0.1.7'''
这种报错，我根据网上的说法进行了修复，重新下载win10SDK，依旧报错
'''error: failed to run custom build command for `rquickjs-sys v0.1.7`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\XXX\Desktop\clash-verge-main\clash-verge\src-tauri\target\debug\build\rquickjs-sys-d1d8d121f0521ced\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\XXX\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rquickjs-sys-0.1.7\build.rs:136:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
     3: core::result::Result<T,E>::unwrap
     4: alloc::slice::hack::into_vec
     5: alloc::slice::hack::into_vec
     6: core::fmt::Arguments::new_const
     7: <alloc::string::String as core::convert::AsRef<[u8]>>::as_ref
     8: std::rt::lang_start
     9: core::ops::function::impls::impl$2::call_once
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\ops\function.rs:287
    10: std::panicking::try::do_call
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:485
    11: std::panicking::try
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:449
    12: std::panic::catch_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panic.rs:140
    13: std::rt::lang_start_internal::closure$2
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\rt.rs:148
    14: std::panicking::try::do_call
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:485
    15: std::panicking::try
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:449
    16: std::panic::catch_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panic.rs:140
    17: std::rt::lang_start_internal
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\rt.rs:148
    18: std::rt::lang_start
    19: main
    20: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    21: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    22: BaseThreadInitThunk
    23: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...'''
请求指教

**Comment by thestmitsuki** [comment]
我使用的是windows系统，22h2
VS2022
最新的稳定版nodejs
最新的LLVM
以及最新的CMAKE

**Comment by thestmitsuki** [comment]
已解决，来自#154
主要原因是windows系统添加环境变量不成功，重启后也无效，最终还是命令行添加变量得以成功
